### ISSUE TITLE
custom grub logo for live image

### ISSUE THREAD

**Issue by birkb** [batchworksde/iksdp_desktop#10]
https://debian-handbook.info/browse/stable/sect.config-bootloader.html
https://debian-live-config.readthedocs.io/en/latest/custom.html

**Comment by schose** [comment]
this is documented here:

https://live-team.pages.debian.net/live-manual/html/live-manual/customizing-binary.en.html
and https://github.com/fsfw-dresden/usb-live-linux/tree/main/features/install_fsfw_grub_theme/install-data/bootloaders/grub-pc

for me it seems more easy to add a splash.png and render the version on top instead of creating a .svg.
